### ISSUE TITLE
Doesn't compile with Boost 1.74

### ISSUE THREAD

**Issue by yemreinci** [hazelcast/hazelcast-cpp-client#732]
The master branch does not compile with the latest Boost release: 1.74.
A similar compile error is emitted both on macos with clang and on linux with gcc.

With 1.74 the error is:
In file included from /Users/ihsan/Desktop/boost_74/include/boost/asio/query.hpp:22:
/Users/ihsan/Desktop/boost_74/include/boost/asio/traits/query_free.hpp:60:14: error: unexpected namespace name 'query': expected expression
    decltype(query(declval<T>(), declval<Property>()))

**Comment by ihsandemir** [comment]
Tested with boost.1.73 and the project compiles.
